### ISSUE TITLE
Version to work with

### ISSUE THREAD

**Issue by LostKobrakai** [mathiasverraes/money#105]
I'm in the means of using this project in one of my own. Now I'm reading that a new version will break backwards compatibility, but the "nextrelease" branch was last updated in February. Is there still work being done or should I better use the older released version?

**Comment by mathiasverraes** [comment]
The current version is very stable, and even if a new version is released,
you'll be able to continue using the old one without problems.

—
Mathias Verraes
Software Consultant
Value Object Comm.V <http://value-object.com>
Blog <http://verraes.net/> - Email <mathias@verraes.net> -  Twitter
<http://twitter.com/mathiasverraes> - LinkedIn
<https://www.linkedin.com/in/mathiasverraes>

**Comment by LostKobrakai** [comment]
Thanks for the clarification. Then I'm going with the stable branch.
