### ISSUE TITLE
lessThanOrEqual not working correctly?

### ISSUE THREAD

**Issue by envision** [mathiasverraes/money#106]
Consider this output:

checking if this value: 15367555 is less than 0
it is less!

For this code:

	echo "checking if this value: ".$value->getAmount()." is less than ".Money::EUR(0)->getAmount();

	if ($value->lessThanOrEqual(Money::EUR(0))) {
		echo "<br> it is less!";
	} else {
		echo "<br> no its not";
	}
	die();

**Comment by sagikazarmark** [comment]
Duplicate of #99
