### ISSUE TITLE
add 'unitsToString' function to Money\Money

### ISSUE THREAD

**Issue by johanwilfer** [mathiasverraes/money#107]
For legacy systems I need to convert to/from floats. To convert I do the following:
```php
use Money\Money;
use Money\Currency;
$float = 123.34;
$money = new Money(Money::stringToUnits((string)$float), new Currency('USD'));
var_dump($money);
/*
object(Money\Money)#2 (2) {
  ["amount":"Money\Money":private]=>
  int(12334)
  ["currency":"Money\Money":private]=>
  object(Money\Currency)#3 (1) {
    ["name":"Money\Currency":private]=>
    string(3) "USD"
  }
}
*/

$float = $money->getAmount() / 100;
var_dump($float);
/*
float(123.34)
*/
```

For example money_format() expects the parameter to be a float: http://php.net/manual/en/function.money-format.php

Shouldn't it make sense to have a unitsToString() in `Money\Money`? Maybe even
unitsToFloat() and floatToUnits() .

I can create a pull-request for this if you would consider including this change.

**Comment by jtallant** [comment]
I really think this would make a lot of sense. I always have to implement it myself. When dealing with money, you're going to need to display it in a user friendly way 99% of the time. The ruby lib supports it https://github.com/RubyMoney/money/blob/master/lib/money/money/formatting.rb

**Comment by johanwilfer** [comment]
Ping @mathiasverraes

**Comment by moon0326** [comment]
+1

**Comment by camspiers** [comment]
https://github.com/sebastianbergmann/money/blob/master/src/Money.php#L131-L134
https://github.com/sebastianbergmann/money-intl-formatter/blob/master/src/IntlFormatter.php

When displaying currency values you should take into account locale as well. The php NumberFormatter class takes care of this. You should also take into account the currencies subunit when doing the division. For example with Yen you should be string 100 Yen as `int(100)` and therefore when you format and display you shouldn't be dividing by 100.

https://en.wikipedia.org/wiki/Denomination_(currency)#Subunit_and_super_unit

**Comment by mathiasverraes** [comment]
Apologies for the neglect to this library. Formatting should, imho, be outside of the Money class, for example in a MoneyFormatting class. PRs welcome (and maintainers also welcome).

**Comment by johanwilfer** [comment]
Formatting is one thing, but some way of getting back to a string (or float) should belong in the Money-class, shouldn't it? I can prepare a PR. I can also help with maintaining if you would like.

Also: there are forks / similar libraries that have unique features (for example big numbers). Is there an interface that we could agree on so that supporting libraries only have to support one interface, or maybe could we merge some of these features in this library?

**Comment by sagikazarmark** [comment]
> Formatting is one thing, but some way of getting back to a string (or float) should belong in the Money-class, shouldn't it?

I don't think so. There are so many ways to represent money as a string, I don't think we should pick one. Also, construction is somehow belongs to the Money object, transformation to other types does not.

> Also: there are forks / similar libraries that have unique features (for example big numbers).

Yeah, this is planned for a long time now. If you have examples, forks which you know, can you pleas link them here so I can take a look?

> Is there an interface that we could agree on

So far, there weren't any as we are talking about a ValueObject.

There is an initiative for standards: https://github.com/e-ig/standards/pull/3

So far, I am not completely satisfied with it as is rather an opinionated thing than a real standard.

> could we merge some of these features in this library?

Absolutely. Do you have some sort of list of these features?

**Comment by frederikbosch** [comment]
My idea would be to create a MoneyFormatter interface with one public method: 'format(Money $money)'. And then an implemention 'IntlMoneyFormatter' inside this package, which should proxy the currency formatter in the intl extension of php. Other people can create their own implementions through the interface.

**Comment by sagikazarmark** [comment]
There is already a third-party formatter interface, see mathiasverraes/money#71.

I am pretty much in favor of the idea.

I wonder if it should be part of this library, or a separate package. I think that maximum half of money representation is actually used for displaying the value, not just working with it, but having the interface and some kind of "default" implementation outside of this package increases complexity.

**Comment by frederikbosch** [comment]
@sagikazarmark In my opinion this library should provide a method how to format a money object, and include one example. So I would include the `MoneyFormatter` interface and the `IntlMoneyFormatter`. Can PR if you'd like.

**Comment by frederikbosch** [comment]
By the way, I do not see how #71 helps us in this case. I read something about an ISO standard and a currency interface, but nothing on formatting.

**Comment by frederikbosch** [comment]
Just found the formatter you are [referencing](https://github.com/antonienko/MoneyFormatter/blob/master/lib/antonienko/MoneyFormatter/MoneyFormatter.php). Personally, I think three public methods is not necessary.

We only need a `format` method. We could return an new (value) object - containing base units, symbol and by locale - but I rather return a string. If someone needs only the only, then he can create a new formatter himself by implementing the interface.

**Comment by sagikazarmark** [comment]
Well, I haven't looked closer at the referenced library, but I knew something is there.

As for MoneyFormatter: I don't actually see a problem having it in this package, so let get this moving. @frederikbosch If you want to provide a PR, that would be great.

I have something in my mind for a long time now: sub unit formatting. The idea is to pass in a subunit, or set of subunits for Currencies (this can be clarified) and modify the value to a float value if necessary. To achieve this, we would need to introduce some kind of ScalarMoneyFormatter which does the same as money formatter, but with scalar values.

Not sure though if it worths the hassle, but we have to provide some way to support subunits in the future.

**Comment by frederikbosch** [comment]
Will do the PR. I do not sure if I understand you on the subunits.

**Comment by sagikazarmark** [comment]
Something like this:

``` php
<?php

$money = new Money(1234, new Currency('EUR'));

$formatter = new SubunitFormatter(new SomeOtherFormatter(), ['EUR' => 100]);

class SubunitFormatter implements MoneyFormatter
{
    protected $delegatedFormatter;

    public function __construct(ScalarMoneyFormatter $delegatedFormatter)
    {
        $this->delegatedFormatter = $delegatedFormatter;
    }

    public function format(Money $money)
    {
        //calculate subunit
        return $this->delegatedFormatter->formatScalar($scalarValue);
    }
}

class SomeOtherFormatter implements MoneyFormatter, ScalarMoneyFormatter { }
```

**Comment by frederikbosch** [comment]
@sagikazarmark Thanks for clearing that, but what would the result be if I call the format method on the `SubunitFormatter`? .34? As in I do not get what you mean by 'subunit'. What value do you need? And why (business case example)?

**Comment by sagikazarmark** [comment]
Nope, 12.34

The point is that subunits are also stored in integers, this way you can display cents and other values.

**Comment by frederikbosch** [comment]
Ah ok, but that is why is done [here](https://github.com/antonienko/MoneyFormatter/blob/master/lib/antonienko/MoneyFormatter/MoneyFormatter.php#L22), right?

**Comment by frederikbosch** [comment]
@sagikazarmark Nonetheless, I will come up with something, then we can discuss whether you like the implementation.

**Comment by sagikazarmark** [comment]
Haven't checked the impl so far, but yes. :+1:

**Comment by frederikbosch** [comment]
Just created PR, please review.

**Comment by sagikazarmark** [comment]
Will do, thank you.

**Comment by frederikbosch** [comment]
This one can be closed as the formatter is merged.
