### ISSUE TITLE
Bugfix release

### ISSUE THREAD

**Issue by pkruithof** [mathiasverraes/money#109]
Issue #43 talks about the next major release (in it you mention 3.0, but seeing the current releases that should be 2.0 I think?). However there are a [number of commits](https://github.com/mathiasverraes/money/compare/1.2.1...master) that contain important bug fixes since the last release, which are not available if you want to use semver in a project.

Until 2.0/3.0 is out, could you tag a new patch release (1.2.2) with the bugfixes?

**Comment by umpirsky** [comment]
:+1: I need bitcoin support.

**Comment by sagikazarmark** [comment]
I will review the changes and tag a release, hopefully this week.

**Comment by umpirsky** [comment]
@sagikazarmark Thanks.

**Comment by sagikazarmark** [comment]
Tagged v1.3.0

**Comment by pkruithof** [comment]
Thanks!
