### ISSUE TITLE
[RFC] Use external updated currency list

### ISSUE THREAD

**Issue by umpirsky** [mathiasverraes/money#124]
I have exported currency list form ICU to various formats, PHP format available https://github.com/umpirsky/currency-list/blob/master/data/en/currency.php.

What do you think about replacing [currencies.php](https://github.com/mathiasverraes/money/blob/master/lib/Money/currencies.php) with this composer dependency and stop worrying about list updates?

**Comment by sagikazarmark** [comment]
I had this in my mind for a long time now. So far I have been looking at the ISO library in #71, but your package looks more "pure" data source.

Would you like to open a PR? If so, please remove the update command and the buzz dependency as well.

**Comment by umpirsky** [comment]
@sagikazarmark Sure, I would like to submit PR, no problem.

Am I missing something or there is no buzz dependency? Can you post link to update command here?

**Comment by sagikazarmark** [comment]
Make sure you are looking at the nextrelease branch:

https://github.com/mathiasverraes/money/blob/nextrelease/bin/update_currencies.php
https://github.com/mathiasverraes/money/blob/nextrelease/composer.json#L18

**Comment by umpirsky** [comment]
@sagikazarmark Oh, ok, thanks!

**Comment by sagikazarmark** [comment]
I have some questions regarding your library in general before merging this to get a clear view:

- What is considered to be a BC break? Removal of currencies? Change in name? Since the code contains some validation features, it is crucial that the same data will always be available in the same version.
- What is the release cycle?

**Comment by umpirsky** [comment]
@sagikazarmark 

> What is considered to be a BC break? Removal of currencies? Change in name? Since the code contains some validation features, it is crucial that the same data will always be available in the same version.

No, I think BC break will be change in data format. For example if we decide to add currency symbol or rounding rules... 

> What is the release cycle?

I hope to update the list few time per year.

**Comment by sagikazarmark** [comment]
What if a user relies on a currency which gets removed?

**Comment by umpirsky** [comment]
@sagikazarmark If you look at https://github.com/umpirsky/currency-list/blob/master/data/en/currency.php even some ancient currencies are still there (e.g. `'YUN' => 'Yugoslavian Convertible Dinar (1990–1992)',`). When updating currency list I will have clear diff and if something gets removed I will notify you.

You can also control exact version of currency list via composer if you want to be 100% sure.

**Comment by sagikazarmark** [comment]
Okay, thanks for clarification.

**Comment by sagikazarmark** [comment]
Closed in #125

**Comment by barryvdh** [comment]
While I would agree that not having to update manually is a plus, but do you realise that the https://github.com/umpirsky/currency-list repository is huge?  It contains 6000+ files and accounts to 90+ MB. And you're just using it 1 load 1 array of currencies?

Why not replace the build script with a call to https://raw.githubusercontent.com/umpirsky/currency-list/master/data/en/currency.php or include the repo as dev-dependancy, and copy the file?  How often do currencies change, I'm guessing not that often..

**Comment by sagikazarmark** [comment]
Hm, I wasn't aware of the fact that it is 90MB+.

I think @umpirsky planned a separate php version of that repository.

@umpirsky any input to what @barryvdh mentioned?

**Comment by frederikbosch** [comment]
@sagikazarmark Why don't we suggest the package of @umpirsky? Just as we suggest intl for formatting and parsing.

@barryvdh Currencies is an interface. It should be no problem to implement it with another library (e.g. alcohol's). However, I do understand the problem of the huge repo. That would be solved by suggesting instead of requiring as I proposed to @sagikazarmark.

**Comment by sagikazarmark** [comment]
To tell the truth, I am not sure that we need ISOCurrencies in the main repo anyway. Since we have an organization, we can separate this component so that we remove all kinds of dependencies from the main package. WDYT?

The package suggestion is a good idea as well, but I think it does not address @barryvdh's concerns, since you still have to install 90MB if you want to use it.

**Comment by frederikbosch** [comment]
@sagikazarmark I would like to see Money as a standalone package without any dependency. But I think we can leave the (intl) formatters and parsers in. There is no need to extract it to another repo. Same for ISOCurrencies. It should be optionsl in the form of a suggestion in the composer.json.

Why would @barryvdh's problem not be solved when we would suggest the package of @umpirsky? Then the user can choose to require it or not. And he obviously would not.

**Comment by umpirsky** [comment]
I think replace the build script with a call to https://raw.githubusercontent.com/umpirsky/currency-list/master/data/en/currency.php or include the repo as dev-dependancy is good idea.

We can also create separate package which include only PHP format with en locale? Will be very tiny.

**Comment by sagikazarmark** [comment]
@frederikbosch The intl extension is somewhat OK because it is a PHP extension, not really an external dependency. However Swap and CurrencyList are external dependencies.

Although if everyone is happy with making the currency list a suggested dependency, then I am fine with it as well.

**Comment by sagikazarmark** [comment]
Oh, just realised that you are suggesting to make it a dev dependency and copy the file. I am fine with that as well. The extra advantage would be removing the extra IO (checking the file existence) operation.
