### ISSUE TITLE
Update README.md, docs and changelog

### ISSUE THREAD

**Issue by frederikbosch** [mathiasverraes/money#137]
We should not forget to update the README and docs when 3.0.0 will be released. It should include.

- [ ] docs
- [x] README.md
- [x] CHANGELOG.md

**Comment by sagikazarmark** [comment]
Changelog as well.

**Comment by barryvdh** [comment]
Is there an estimated planning for a stable 3.0 release?

**Comment by frederikbosch** [comment]
@barryvdh We have two failing tests left in my [two](https://github.com/mathiasverraes/money/pull/149) [PRs](https://github.com/mathiasverraes/money/pull/148). Then there will be a release (I guess).

**Comment by frederikbosch** [comment]
I haven't found time to look into it. It would be really helpful if someone can help out. I am not an `intl` expert.

**Comment by sagikazarmark** [comment]
Well, the same as HTTPlug. :smile: 

As you said, it's Open Source, so timing does not always happen as planned.

We have some open PRs to be merged, some of them are critical. Also, some issues could be addressed in 3.0. After that I would like to go through the usual alpha-beta-release process.

**Comment by barryvdh** [comment]
Ha, yeah I'm asking for the same reason, also Omnipay v3 ;)

And I'm not in a rush, just curious if it's close or still far away :)

**Comment by frederikbosch** [comment]
It's close. I would love to see Omnipay with Money :+1:

**Comment by sagikazarmark** [comment]
I would say rather close than far. No more big changes planned, only the current issues.

**Comment by sagikazarmark** [comment]
Docs already has an issue
