### ISSUE TITLE
Umpirsky/currency-list won't work

### ISSUE THREAD

**Issue by sagikazarmark** [mathiasverraes/money#139]
@umpirsky Will this work when this package is installed as a dependency?

https://github.com/mathiasverraes/money/blob/nextrelease/src/ISOCurrencies.php#L21

I think not.

The path in that case will be:

`__DIR__.'/../../../umpirsky/currency-list/data/en/currency.php'`

**Comment by umpirsky** [comment]
@sagikazarmark Good catch, thanks!

Proposed fix in https://github.com/mathiasverraes/money/pull/140.
