### ISSUE TITLE
Casting to (string) relies on PHP `precision` setting to be between 3 and 8 to work as expected

### ISSUE THREAD

**Issue by judgej** [mathiasverraes/money#151]
I noticed in the constructor for `Number` you do a `(string) $number`.

https://github.com/mathiasverraes/money/blob/nextrelease/src/Number.php#L25

We had [some problems doing this on OmniPay](https://github.com/thephpleague/omnipay-common/issues/69) when changing a float to a string, as the string it creates will depend on the accuracy that the current PHP system is set up.

To avoid some unexpected results on a system setting that is not under the control of a currency package, you can use `sprintf()` to force a specific accuracy each time, instead of leaving it for PHP to use whatever `precision` setting it happens to have.

**Comment by sagikazarmark** [comment]
Hey @judgej 

Thanks for reporting the issue, good catch.

If you have already fixed this issue, can you link us to an existing solution/in what context you used this? Just for curiosity. Thanks

**Comment by barryvdh** [comment]
The proposed fix is here: https://github.com/thephpleague/omnipay-common/pull/70/files
If you both agree that's a good solution, that would be great :)

**Comment by frederikbosch** [comment]
Frankly, I do not get why this an issue of `Money`. The conversion to float does not happen in this library, right?

**Comment by sagikazarmark** [comment]
You are right, Money does not accept other than an integer value. However, it is an issue of Number object, which we might use in a PreciseMoney.

**Comment by judgej** [comment]
There's a [PR here](https://github.com/judgej/omnipay-common/commit/529b18fe6b3196b4606b28548cb97ee913eaa914).

I say a constructor with an open parameter that did `(string)$number`, so assuming a float could go into that constructor (since nothing is stopping that ATM) then that's why this is a heads up.

**Comment by sagikazarmark** [comment]
@judgej Number is currently used internally. From Money's public API there is no way you pass a float value in, but there is a chance that the Number class will be used in the future where this could actually cause an issue (PreciseMoney).

**Comment by frederikbosch** [comment]
@judgej Ah, alright. You are consuming the `Number` class standalone. I get it. PR is on the way.

**Comment by frederikbosch** [comment]
Fix pushed, waiting for PR to be merged.

**Comment by sagikazarmark** [comment]
PR merged, this can be closed I guess. Thanks everyone.

**Comment by judgej** [comment]
That was a whirlwind of a change. Thanks!
