### ISSUE TITLE
Calculator Question

### ISSUE THREAD

**Issue by browner12** [mathiasverraes/money#153]
About a year ago I submitted a proposal to the PHP League of my implementation of a money package. I got good feedback from both @mathiasverraes and @sagikazarmark. I had proposed separating responsibilities out into both a `Money` class and an `Accountant` class. You both argued that money should inherently know how to do math on itself, and that an `Accountant` was unnecessary.  Now as I look at your `nextrelease` branch of your money package I see that you guys have created `Calculator`s, which I believe is exactly what I was proposing.  I'd love to talk with you guys a bit about what made you change your minds on this issue.

Thanks!

**Comment by frederikbosch** [comment]
@browner12 The `Calculator` class was made in order to support unlimited integer support (bigger than PHP_MAX_INT) through `gmp` and `bc`. See #111.

**Comment by frederikbosch** [comment]
Reasoning and design decisions to be found with the PR at #115.

**Comment by sagikazarmark** [comment]
@browner12 I am not completely sure I remember what exactly your design was. But if I am correct, your "Calculators" were "outside" of the Money API. While our calculators are encapsulated into the Money object API. It is an internal detail which allow us to use various numeric value handling. Hope that answers your question.

**Comment by browner12** [comment]
thanks @frederikbosch 

yup, @sagikazarmark, that was it.  mine was external rather than being a dependency of my `Money`. thanks for the reply.
