### ISSUE TITLE
remove deprecated features

### ISSUE THREAD

**Issue by mathiasverraes** [mathiasverraes/money#45]

**Comment by sagikazarmark** [comment]
What deprecated features exactly @mathiasverraes ?

**Comment by frederikbosch** [comment]
@sagikazarmark 

- [getName in `Currency`](https://github.com/mathiasverraes/money/blob/nextrelease/src/Currency.php#L40)
- [getRatio in `CurrencyPair`](https://github.com/mathiasverraes/money/blob/nextrelease/src/CurrencyPair.php#L126)
- [getUnits in `Money`](https://github.com/mathiasverraes/money/blob/nextrelease/src/Money.php#L203)

**Comment by frederikbosch** [comment]
PR in #135.

**Comment by sagikazarmark** [comment]
Cool :+1:
