### ISSUE TITLE
Provide IDE hints for static methods (eg, Money::USD(5000))

### ISSUE THREAD

**Issue by jrdnhannah** [mathiasverraes/money#70]
The Money library allows the currency to be used as a static method, ie:

`$money = Money::USD(5000);`

However, these static methods are dynamic and picked up by `Money::__callStatic`, which means there's no IDE hinting, so the IDE doesn't know it exists, and won't infer that `$money` is a Money type.

The methods can be annotated on the Money class, though, like in [beberlei/assert](https://github.com/beberlei/assert/blob/master/lib/Assert/AssertionChain.php), and this will provide IDE integration.

If this is something which you would be interested in @mathiasverraes, I'll implement it then submit a PR :)

**Comment by davidkalosi** [comment]
Here it is since this somehow went unnoticed https://github.com/mathiasverraes/money/pull/92

**Comment by jrdnhannah** [comment]
Oh wow I completely forgot about this! Sorry >.<

**Comment by sagikazarmark** [comment]
Since the library is not depending on ISO currencies any more, I wonder if it is a good idea.

**Comment by sagikazarmark** [comment]
The relevant PR is closed.
