### ISSUE TITLE
Sharing is caring (iso4217)

### ISSUE THREAD

**Issue by alcohol** [mathiasverraes/money#71]
I was told by a reddit user that you might perhaps be interested in having a look @ https://github.com/alcohol/iso4217

Feel free to close this issue at any time :-)

**Comment by sovaalexandr** [comment]
Also came to suggest same library instead of using `currencies.php`

**Comment by antonienko** [comment]
Based on this issue, I've created [this helper](https://github.com/antonienko/MoneyFormatter), that maybe somebody can find useful.

**Comment by sagikazarmark** [comment]
Hey guys,

These things look very interesting, I would like to bring these libraries closer.

**Comment by sagikazarmark** [comment]
Thanks for sharing guys.

@alcohol we rely on a currency list added in #125

@antonienko based on your work there is this is WIP: #123
