### ISSUE TITLE
Is there a way to get the float number?

### ISSUE THREAD

**Issue by herlon214** [mathiasverraes/money#78]
This lib has some function to get the float number? Example: 1270 get -> 12.70 ?

Thanks in advance, and sorry for the newbie question.

**Comment by mathiasverraes** [comment]
getAmount() / 100

**Comment by teohhanhui** [comment]
Now that Money::getAmount returns a string, we can just do

```php
substr_replace($orderSubtotalMoney->getAmount(), '.', '-2', 0)
```

to obtain the actual amount as string (say, perhaps you want to store the value as "decimal"/"numeric" type in the database).

**Comment by sagikazarmark** [comment]
Thanks for the tip @teohhanhui

**Comment by teohhanhui** [comment]
Shouldn't we add this as a convenience method?

**Comment by sagikazarmark** [comment]
@teohhanhui I would prefer keeping money clear from convenience stuff.
