### ISSUE TITLE
Support for digital currencies

### ISSUE THREAD

**Issue by josecelano** [mathiasverraes/money#79]
Add digital currencies to currencies.php array (at least bitcoin).

**Comment by mathiasverraes** [comment]
Merged the PR. In the 3.0 release, it will be easier to use your own currencies.

**Comment by josecelano** [comment]
Thanks!

**Comment by josecelano** [comment]
Bitcoin has 8 decimal places and the maximun amount available will be 21 millions (when bitcoin mining ends). Decimal places of bitcoins are called "satoshis". 21 millions converted to satoshis would be: 21.000.000 * 10^8 which is greater than max integer in 32-bit system (2.147.483.647). 

Therefore, it is not sufficient to add BTC to currencies list.

I have read in this issue:
https://github.com/mathiasverraes/money/issues/7
that your are planning to add BigMoney class to allow decimal scalabilitty. In the bitocin case it is needed scalability even without using more than 8 decimals, but It seems you do not like using float as I have read here:
https://github.com/mathiasverraes/money/pull/55/files#r16972250

With int type max value (32 bit system), bitcoin amount would be 21.47483648 satoshis which is a very small amount.

Could bitcoin be used with that BigMoney class?

**Comment by josecelano** [comment]
Could be possible to use DecimalN like this:
https://github.com/ikr/money-math-php/tree/master/src/MoneyMath instead of int?
