### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by egrego-dot-re** [mathiasverraes/money#82]
So...

    <?php

    require_once "vendor/autoload.php";

    $tenDollars = Money\Money::USD(10);

    $divided = $tenDollars->divide(0);

    echo $divided->getAmount();

... produces 0 and a warning, no exception. Is that by design?

**Comment by mathiasverraes** [comment]
No :-)
Got a pull request?

**Comment by egrego-dot-re** [comment]
Can do in a while, but I have something even nicer for you, I will publish it from company account today, Keios.
