### ISSUE TITLE
$ not supported by stringToUnits()

### ISSUE THREAD

**Issue by thedavidmeister** [mathiasverraes/money#98]
I tried to get '$100' to be some Money units using stringToUnits() but got "The value could not be parsed as money".

**Comment by thedavidmeister** [comment]
FYI http://stackoverflow.com/questions/14169820/regular-expression-to-match-all-currency-symbols

**Comment by thedavidmeister** [comment]
````
$string = preg_replace('@\p{Sc}*@', '', $string);
````

**Comment by thedavidmeister** [comment]
https://github.com/mathiasverraes/money/pull/101

**Comment by frederikbosch** [comment]
While #101 has been merged. It might be an idea to also create a `MoneyParser` interface with a `IntlMoneyParser` implementation. By using `ext/intl` the support for different notations will be - I guess - much larger.

@sagikazarmark What do you think?

**Comment by frederikbosch** [comment]
The current `stringToUnit` method might become `StringToUnitParser`.

**Comment by frederikbosch** [comment]
Should be fixed in #148.

**Comment by sagikazarmark** [comment]
Fixed in #148
